package imise.encoding;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

public class AnsiEncoder {

	static Map<String, String> ansiMap = new HashMap<String, String>();
	static {
		ansiMap.put("€", "&#128;");
		ansiMap.put("‚", "&#130;");
		ansiMap.put("ƒ", "&#131;");
		ansiMap.put("„", "&#132;");
		ansiMap.put("…", "&#133;");
		ansiMap.put("†", "&#134;");
		ansiMap.put("‡", "&#135;");
		ansiMap.put("ˆ", "&#136;");
		ansiMap.put("‰", "&#137;");
		ansiMap.put("Š", "&#138;");
		ansiMap.put("‹", "&#139;");
		ansiMap.put("Œ", "&#140;");
		ansiMap.put("", "&#142;");
		ansiMap.put("‘", "&#145;");
		ansiMap.put("’", "&#146;");
		ansiMap.put("“", "&#147;");
		ansiMap.put("”", "&#148;");
		ansiMap.put("•", "&#149;");
		ansiMap.put("–", "&#150;");
		ansiMap.put("—", "&#151;");
		ansiMap.put("˜", "&#152;");
		ansiMap.put("™", "&#153;");
		ansiMap.put("š", "&#154;");
		ansiMap.put("›", "&#155;");
		ansiMap.put("œ", "&#156;");
		ansiMap.put("", "&#158;");
		ansiMap.put("Ÿ", "&#159;");
		ansiMap.put("¡", "&#161;");
		ansiMap.put("¢", "&#162;");
		ansiMap.put("£", "&#163;");
		ansiMap.put("¤", "&#164;");
		ansiMap.put("¥", "&#165;");
		ansiMap.put("¦", "&#166;");
		ansiMap.put("§", "&#167;");
		ansiMap.put("¨", "&#168;");
		ansiMap.put("©", "&#169;");
		ansiMap.put("ª", "&#170;");
		ansiMap.put("«", "&#171;");
		ansiMap.put("¬", "&#172;");
		ansiMap.put("­", "&#173;");
		ansiMap.put("®", "&#174;");
		ansiMap.put("¯", "&#175;");
		ansiMap.put("°", "&#176;");
		ansiMap.put("±", "&#177;");
		ansiMap.put("²", "&#178;");
		ansiMap.put("³", "&#179;");
		ansiMap.put("´", "&#180;");
		ansiMap.put("µ", "&#181;");
		ansiMap.put("¶", "&#182;");
		ansiMap.put("·", "&#183;");
		ansiMap.put("¸", "&#184;");
		ansiMap.put("¹", "&#185;");
		ansiMap.put("º", "&#186;");
		ansiMap.put("»", "&#187;");
		ansiMap.put("¼", "&#188;");
		ansiMap.put("½", "&#189;");
		ansiMap.put("¾", "&#190;");
		ansiMap.put("¿", "&#191;");
		ansiMap.put("À", "&#192;");
		ansiMap.put("Á", "&#193;");
		ansiMap.put("Â", "&#194;");
		ansiMap.put("Ã", "&#195;");
		ansiMap.put("Ä", "&#196;");
		ansiMap.put("Å", "&#197;");
		ansiMap.put("Æ", "&#198;");
		ansiMap.put("Ç", "&#199;");
		ansiMap.put("È", "&#200;");
		ansiMap.put("É", "&#201;");
		ansiMap.put("Ê", "&#202;");
		ansiMap.put("Ë", "&#203;");
		ansiMap.put("Ì", "&#204;");
		ansiMap.put("Í", "&#205;");
		ansiMap.put("Î", "&#206;");
		ansiMap.put("Ï", "&#207;");
		ansiMap.put("Ğ", "&#208;");
		ansiMap.put("Ñ", "&#209;");
		ansiMap.put("Ò", "&#210;");
		ansiMap.put("Ó", "&#211;");
		ansiMap.put("Ô", "&#212;");
		ansiMap.put("Õ", "&#213;");
		ansiMap.put("Ö", "&#214;");
		ansiMap.put("×", "&#215;");
		ansiMap.put("Ø", "&#216;");
		ansiMap.put("Ù", "&#217;");
		ansiMap.put("Ú", "&#218;");
		ansiMap.put("Û", "&#219;");
		ansiMap.put("Ü", "&#220;");
		ansiMap.put("İ", "&#221;");
		ansiMap.put("Ş", "&#222;");
		ansiMap.put("ß", "&#223;");
		ansiMap.put("à", "&#224;");
		ansiMap.put("á", "&#225;");
		ansiMap.put("â", "&#226;");
		ansiMap.put("ã", "&#227;");
		ansiMap.put("ä", "&#228;");
		ansiMap.put("å", "&#229;");
		ansiMap.put("æ", "&#230;");
		ansiMap.put("ç", "&#231;");
		ansiMap.put("è", "&#232;");
		ansiMap.put("é", "&#233;");
		ansiMap.put("ê", "&#234;");
		ansiMap.put("ë", "&#235;");
		ansiMap.put("ì", "&#236;");
		ansiMap.put("í", "&#237;");
		ansiMap.put("î", "&#238;");
		ansiMap.put("ï", "&#239;");
		ansiMap.put("ğ", "&#240;");
		ansiMap.put("ñ", "&#241;");
		ansiMap.put("ò", "&#242;");
		ansiMap.put("ó", "&#243;");
		ansiMap.put("ô", "&#244;");
		ansiMap.put("õ", "&#245;");
		ansiMap.put("ö", "&#246;");
		ansiMap.put("÷", "&#247;");
		ansiMap.put("ø", "&#248;");
		ansiMap.put("ù", "&#249;");
		ansiMap.put("ú", "&#250;");
		ansiMap.put("û", "&#251;");
		ansiMap.put("ü", "&#252;");
		ansiMap.put("ı", "&#253;");
		ansiMap.put("ş", "&#254;");
		ansiMap.put("ÿ", "&#255;");
	}

	public static String replaceAllAnsi(String in) {
		String out = "" + in;
		for (Iterator<String> ansichars = ansiMap.keySet().iterator(); ansichars.hasNext();) {
			String readChar = (String) ansichars.next();
			// System.out.println(readChar+ " is in "+out.contains(readChar));
			out = out.replaceAll(readChar, ansiMap.get(readChar));
		}
		return out;
	}
}
